var walletLanguages = {
	'en': {
		'lang-alias': 'English',
		'wallet-title': 'Wallet',
		'open-regular': 'Regular wallet',
		'open-key': 'Open by key',
		'disclaimer': 'This page uses javascript to generate your addresses and sign your transactions within your browser, this means we never receive your private keys, this can be independently verified by reviewing the source code on Github.',
		'open-reminder': '<b>Notice:</b> Please make sure that you remember your account details, otherwise you may lose access to your funds.',
		'open': 'Open',
		'home': 'Home',
		'create': 'Create',
		'broadcast': 'Broadcast',
		'settings': 'Settings',
		'email-address': 'Email address',
		'password': 'Password',
		'password-confirm': 'Confirm password',
		'generate-question': 'Still don\'t have wallet?',
		'generate-it': '<a href="#/create">Generate</a> it!',
		'wif-key': 'WIF Private key',
		'create-wallet': 'Create wallet',
		'show': 'Show',
		'hide': 'Hide',
		'address': 'Address',
		'public-key': 'Public Key',
		'private-key': 'Private Key',
		'broadcast-transaction': 'Broadcast transaction',
		'enter-transaction': 'Enter your signed transaction',
		'wallet-settings': 'Wallet settings',
		'address-type': 'Address Type',
		'wallet-backend': 'Wallet Backend',
		'update': 'Update',
		'wallet-language': 'Wallet Language',
		'version': 'Version:',
		'wallet': 'Wallet',
		'close': 'Close',
		'send': 'Send',
		'history': 'Hisotry',
		'keys': 'Keys',
		'reset': 'Reset',
		'available-balance': 'Available balance:',
		'enter-address': 'Enter address',
		'amount': 'Amount',
		'fee': 'Fee',
		'recommended': 'recommended',
		'loading': 'Loading...',
		'send-sure': 'Are you sure?',
		'send-processing': 'Processing...',
		'success': 'Success',
		'failed': 'Failed',
		'send-it': 'Yes, send it!',
		'cancel': 'Cancel',
		'send-warning': 'You are one step away from sending',
		'send-warning-reverse': 'This action <strong>cannot</strong> be reversed. Are you sure about this?',
		'loading-utxo': 'Loading UTXOs...',
		'transaction-creation': 'Creating transaction...',
		'transaction-broadcasted': 'Transaction successfully broadcasted: ',
		'close': 'Close',
		'address-type-changed': 'Address type changed to',
		'backend-switched': 'Backend is switched to',
		'backend-down': 'don\'t seems to be available',
		'wallet-api': 'Wallet API backend',
		'open-wallet': 'Open Wallet',
		'bad-utxo': 'Unsupported UTXO type!',
		'balance-load-failed': 'We couldn\'t load wallet balance!',
		'not-enough-funds': 'You don\'t have enough funds for this transaction!',
		'not-valid-address': 'You must specify valid address!',
		'not-valid-amount': 'You must specify valid amount!',
		'not-valid-fee': 'You must specify valid fee!',
		'bad-priv-key': 'Bad WIF private key!',
		'not-enough-utxo': 'Not enough UTXO :(',
		'broadcast-failed': 'Transaction broadcast failed :(',
		'pass-not-match': 'Your passwords do not match!',
		'pass-too-short': 'Your password must be at least 10 chars long!',
		'bad-email': 'Your email address doesn\'t appear to be valid!',
		'small-fee': 'You should specify fee not less than'
	},
	'uk': {
		'lang-alias': 'Українська',
		'wallet-title': 'Гаманець',
		'open-regular': 'Звичайний гаманець',
		'open-key': 'Відкрити ключем',
		'disclaimer': 'Ця сторінка використовує javascript для генерації ваших адрес та підпису транзакцій всередині браузера, це означає, що ми ніколи не отримуємо ваші приватні ключі, це можна перевірити незалежно, переглянувши вихідний код на Github.',
		'open-reminder': '<b>Увага:</b> Будь ласка переконайтесь, що ви запам\'ятали дані вашого акаунту, інакше ви можете втратити доступ до ваших коштів.',
		'open': 'Відкрити',
		'home': 'Домівка',
		'create': 'Створити',
		'broadcast': 'Транслювати',
		'settings': 'Налаштування',
		'email-address': 'Електронна пошта',
		'password': 'Пароль',
		'password-confirm': 'Підтвердіть пароль',
		'generate-question': 'Все ще не маєте гаманця?',
		'generate-it': '<a href="#/create">Згенеруйте</a> його!',
		'wif-key': 'Приватний ключ WIF',
		'create-wallet': 'Створити гаманець',
		'show': 'Показати',
		'hide': 'Сховати',
		'address': 'Адреса',
		'public-key': 'Публічний Ключ',
		'private-key': 'Приватний Ключ',
		'broadcast-transaction': 'Транслювати транзакцію',
		'enter-transaction': 'Введіть вашу підписану транзакцію',
		'wallet-settings': 'Налаштування гаманця',
		'address-type': 'Тип Адреси',
		'wallet-backend': 'Бекенд Гаманця',
		'update': 'Оновити',
		'wallet-language': 'Мова Гаманця',
		'version': 'Версія:',
		'wallet': 'Гаманець',
		'close': 'Закрити',
		'send': 'Надіслати',
		'history': 'Історія',
		'keys': 'Ключі',
		'reset': 'Скинути',
		'available-balance': 'Доступний баланс:',
		'enter-address': 'Введіть адресу',
		'amount': 'Сума',
		'fee': 'Комісія',
		'recommended': 'рекомендовано',
		'loading': 'Завантаження...',
		'send-sure': 'Ви впевенені?',
		'send-processing': 'Обробка...',
		'success': 'Успіх',
		'failed': 'Невдача',
		'send-it': 'Так, надіслати!',
		'cancel': 'Скасувати',
		'send-warning': 'Ви в одному кроці від того, щоб надіслати',
		'send-warning-reverse': 'Ця дія <strong>не може</strong> бути скасованою. Ви впевнені?',
		'loading-utxo': 'Завантаження UTXOs...',
		'transaction-creation': 'Створення транзакції...',
		'transaction-broadcasted': 'Транзакція успішно надіслана: ',
		'close': 'Закрити',
		'address-type-changed': 'Тип адрес змінений на',
		'backend-switched': 'Бекенд змінений на',
		'backend-down': 'виглядає мертвим',
		'wallet-api': 'API Бекенд гаманця',
		'open-wallet': 'Відкрити Гаманець',
		'bad-utxo': 'Непідтримуваний тип UTXO!',
		'balance-load-failed': 'Нам не вдалося завантажити баланс вашого гаманця!',
		'not-enough-funds': 'У вас не достатньо коштів для цієї транзакції!',
		'not-valid-address': 'Ви маєте ввести дійсну адресу!',
		'not-valid-amount': 'Ви маєте ввести дійсну суму!',
		'not-valid-fee': 'Ви маєте ввести дійсну комісію!',
		'bad-priv-key': 'Недійсний WIF приватний ключ WIF!',
		'not-enough-utxo': 'Не достатньо UTXO :(',
		'broadcast-failed': 'Не вдалося транслювати транзакцію :(',
		'pass-not-match': 'Паролі не не збігаються!',
		'pass-too-short': 'Ваш пароль повинен бути не менше 10 символів!',
		'bad-email': 'Схоже, що ви ввели не дійсну поштову скриньку!',
		'small-fee': 'Ви маєте задати комісію не менше ніж'
	},
	'id': {
		'lang-alias': 'Indonesian',
		'wallet-title' : 'Wallet',
		'open-regular': 'Buka dompet',
		'open-key': 'Buka dengan kunci',
		'disclaimer': 'Halaman ini menggunakan javascript untuk menghasilkan alamat dompet dan menandatangani transaksi Anda, ini berarti kami tidak pernah menerima kunci domprt pribadi Anda, ini diverifikasi secara terpisah dengan melihat sumber code di Github.',
		'open-reminder': '<b>Perhatikan:</b> Pastikan Anda mencadangkan detail dompet anda, jika tidak, Anda dapat kehilangan akses ke dana Anda.',
		'open': 'Buka',
		'home': 'Halaman depan',
		'create': 'Membuat',
		'broadcast': 'Siaran',
		'settings': 'Pengaturan',
		'email-address': 'Alamat Email',
		'password': 'Kata Kunci',
		'password-confirm': 'Konfirmasi Kata Kunci',
		'generate-question': 'sudah punya dompet\belum punya dompet?',
		'generate-it': '<a href="#/create">Membuat</a> dompet!',
		'wif-key': 'WIF Kunci Pribadi',
		'create-wallet': 'Membuat Dompet',
		'show': 'Tunjukan',
		'hide': 'Sembunyikan',
		'address': 'Alamat',
		'public-key': 'Kunci Publik',
		'private-key': 'Kunci Pribadi',
		'broadcast-transaction': 'Siaran transaksi',
		'enter-transaction': 'masuk transaksi',
		'wallet-settings': 'Pengaturan Dompet',
		'address-type': 'Tipe Alamat',
		'wallet-backend': 'Backend Dompet',
		'update': 'Pembaharuan',
		'wallet-language': 'Bahasa dompet',
		'version': 'Versi:',
		'wallet': 'Dompet',
		'close': 'Tutup',
		'send': 'Kirim',
		'history': 'Riwayat',
		'keys': 'Kunci',
		'reset': 'Mulai ulang',
		'available-balance': 'Saldo tersedia:',
		'enter-address': 'Masukan Alamat',
		'amount': 'Jumlah',
		'fee': 'Biaya',
		'recommended': 'Rekomendasi',
		'loading': 'Memuat...',
		'send-sure': 'Apakah kamu Yakin?',
		'send-processing': 'Memproses...',
		'success': 'Sukses',
		'failed': 'Gagal',
		'send-it': 'Ya, Kirim sekarang!',
		'cancel': 'Batalkan',
		'send-warning': 'Tinggal selangkah lagi',
		'send-warning-reverse': 'Tetap kirim <strong>Batalkan</strong> bisa kembali. Apa kamu sudah yakin?',
		'loading-utxo': 'Memuat UTXOs...',
		'transaction-creation': 'Membuat Transaksi...',
		'transaction-broadcasted': 'Transaksi berhasil dikirim: ',
		'close': 'Tutup',
		'address-type-changed': 'Ganti tipe alamat',
		'backend-switched': 'Backend berpindah ke',
		'backend-down': 'Backend sepertinya tidak ada',
		'wallet-api': 'Dompet API',
		'open-wallet': 'Buka Dompet',
		'bad-utxo': 'Tidak mendukung tipe UTXO!',
		'balance-load-failed': 'Kami tidak bisa menampilkan jumlah saldo!',
		'not-enough-funds': 'Kamu tidak punya cukup saldo untuk transaksi ini!',
		'not-valid-address': 'Kamu harus memasukkan wallet yang benar!',
		'not-valid-amount': 'Kamu harus memasukkan jumlah yang benar!',
		'not-valid-fee': 'Kamu harus memasukkan biaya yang benar!',
		'bad-priv-key': 'Kunci Pribadi Salah!',
		'not-enough-utxo': 'Tidak Cukup UTXO :(',
		'broadcast-failed': 'Siaran transaksi gagal :(',
		'pass-not-match': 'Password anda tidak cocok!',
		'pass-too-short': 'Kata sandi Anda setidaknya harus sepanjang 10 karakter!',
		'bad-email': 'Alamat email Anda tampaknya tidak valid!',
		'small-fee': 'Biaya terlalu kecil'
	},
	'ja': {
		'lang-alias': '日本語',
		'open-regular': '通常ウォレット',
		'open-key': 'キーで開く',
		'disclaimer': 'このページではjavascriptを使用してアドレスを生成し、ブラウザ内でトランザクションに署名します。そのため、秘密鍵を送信することはありません。これはGithubのソースコードで確認できます。',
		'open-reminder': '<b>お知らせ:</b> アカウント詳細を忘れないようにしてください。残高にアクセスできなくなる可能性があります。',
		'open': '開く',
		'home': 'ホーム',
		'create': '作成',
		'broadcast': 'ブロードキャスト',
		'settings': '設定',
		'email-address': 'メールアドレス',
		'password': 'パスワード',
		'password-confirm': 'パスワード確認',
		'generate-question': 'まだウォレットを持っていませんか？',
		'generate-it': '<a href="#/create">作ります！</a> ',
		'wif-key': 'WIF形式の秘密鍵',
		'create-wallet': 'ウォレット作成',
		'show': '見る',
		'hide': '隠す',
		'address': 'アドレス',
		'public-key': '公開鍵',
		'private-key': '暗号鍵',
		'broadcast-transaction': 'トランザクションのブロードキャスト',
		'enter-transaction': 'トランザクションを入力してください',
		'wallet-settings': 'ウォレット設定',
		'address-type': 'アドレスタイプ',
		'wallet-backend': 'ウォレットバックエンド',
		'update': '更新',
		'wallet-language': 'ウォレット言語',
		'version': 'バージョン:',
		'wallet': 'ウォレット',
		'close': '閉じる',
		'send': '送信',
		'history': '履歴',
		'keys': 'キー',
		'reset': 'リセット',
		'available-balance': '利用可能:',
		'enter-address': 'アドレスを入力してください',
		'amount': '金額',
		'fee': '手数料',
		'recommended': '推奨',
		'loading': '読み込み中...',
		'send-sure': '送信してよろしいですか？',
		'send-processing': '処理中...',
		'success': '成功',
		'failed': '失敗',
		'send-it': 'はい、送信します！',
		'cancel': 'キャンセル',
		'send-warning': '送信までもうひと段階です',
		'send-warning-reverse': 'この操作は<strong>取消できません。</strong>本当によろしいですか？',
		'loading-utxo': 'UTXOsを読み込んでいます...',
		'transaction-creation': 'トランザクションを作成中...',
		'transaction-broadcasted': 'トランザクションのブロードキャストに成功しました: ',
		'close': '閉じる',
		'address-type-changed': 'アドレスタイプの変更',
		'backend-switched': 'バックエンドの変更',
		'backend-down': '使用不可能',
		'wallet-api': 'ウォレットAPIバックエンド',
		'open-wallet': 'ウォレットを開く',
		'bad-utxo': 'サポートされていないUTXOタイプです！',
		'balance-load-failed': 'ウォレット残高が読み込めませんでした！',
		'not-enough-funds': 'トランザクション金額不足',
		'not-valid-address': '正しいアドレスを指定してください！',
		'not-valid-amount': '正しい金額を指定してください！',
		'not-valid-fee': '正しい手数料を指定してください！',
		'bad-priv-key': '秘密鍵が間違っています',
		'not-enough-utxo': 'UTXOが不足しています :(',
		'broadcast-failed': 'トランザクションのブロードキャストに失敗しました :(',
		'pass-not-match': 'パスワードが間違っています！',
		'pass-too-short': 'パスワードは10文字以上必要です！',
		'bad-email': 'メールアドレスが登録されていません！',
		'small-fee': '最低手数料'
	}
}