var walletLanguages = {
	'en': {
		'lang-alias': 'English',
		'wallet-title': 'Walelt',
		'open-regular': 'Regular wallet',
		'open-key': 'Open by key',
		'disclaimer': 'This page uses javascript to generate your addresses and sign your transactions within your browser, this means we never receive your private keys, this can be independently verified by reviewing the source code on Github.',
		'open-reminder': '<b>Notice:</b> Please make sure that you remember your account details, otherwise you may lose access to your funds.',
		'open': 'Open',
		'home': 'Home',
		'create': 'Create',
		'broadcast': 'Broadcast',
		'settings': 'Settings',
		'email-address': 'Email address',
		'password': 'Password',
		'password-confirm': 'Confirm password',
		'generate-question': 'Still don\'t have wallet?',
		'generate-it': '<a href="#/create">Generate</a> it!',
		'wif-key': 'WIF Private key',
		'create-wallet': 'Create wallet',
		'show': 'Show',
		'hide': 'Hide',
		'address': 'Address',
		'public-key': 'Public Key',
		'private-key': 'Private Key',
		'broadcast-transaction': 'Broadcast transaction',
		'enter-transaction': 'Enter your signed transaction',
		'wallet-settings': 'Wallet settings',
		'address-type': 'Address Type',
		'wallet-backend': 'Wallet Backend',
		'update': 'Update',
		'wallet-language': 'Wallet Language',
		'version': 'Version:',
		'wallet': 'Wallet',
		'close': 'Close',
		'send': 'Send',
		'history': 'Hisotry',
		'keys': 'Keys',
		'reset': 'Reset',
		'available-balance': 'Available balance:',
		'enter-address': 'Enter address',
		'amount': 'Amount',
		'fee': 'Fee',
		'recommended': 'recommended',
		'loading': 'Loading...',
		'send-sure': 'Are you sure?',
		'send-processing': 'Processing...',
		'success': 'Success',
		'failed': 'Failed',
		'send-it': 'Yes, send it!',
		'cancel': 'Cancel',
		'send-warning': 'You are one step away from sending',
		'send-warning-reverse': 'This action <strong>cannot</strong> be reversed. Are you sure about this?',
		'loading-utxo': 'Loading UTXOs...',
		'transaction-creation': 'Creating transaction...',
		'transaction-broadcasted': 'Transaction successfully broadcasted: ',
		'close': 'Close',
		'address-type-changed': 'Address type changed to',
		'backend-switched': 'Backend is switched to',
		'backend-down': 'don\'t seems to be available',
		'wallet-api': 'Wallet API backend',
		'open-wallet': 'Open Wallet',
		'bad-utxo': 'Unsupported UTXO type!',
		'balance-load-failed': 'We couldn\'t load wallet balance!',
		'not-enough-funds': 'You don\'t have enough funds for this transaction!',
		'not-valid-address': 'You must specify valid address!',
		'not-valid-amount': 'You must specify valid amount!',
		'not-valid-fee': 'You must specify valid fee!',
		'bad-priv-key': 'Bad WIF private key!',
		'not-enough-utxo': 'Not enough UTXO :(',
		'broadcast-failed': 'Transaction broadcast failed :(',
		'pass-not-match': 'Your passwords do not match!',
		'pass-too-short': 'Your password must be at least 10 chars long!',
		'bad-email': 'Your email address doesn\'t appear to be valid!',
		'small-fee': 'You should specify fee not less than'
	},
	'uk': {
		'lang-alias': 'Українська',
		'wallet-title': 'Гаманець',
		'open-regular': 'Звичайний гаманець',
		'open-key': 'Відкрити ключем',
		'disclaimer': 'Ця сторінка використовує javascript для генерації ваших адрес та підпису транзакцій всередині браузера, це означає, що ми ніколи не отримуємо ваші приватні ключі, це можна перевірити незалежно, переглянувши вихідний код на Github.',
		'open-reminder': '<b>Увага:</b> Будь ласка переконайтесь, що ви запам\'ятали дані вашого акаунту, інакше ви можете втратити доступ до ваших коштів.',
		'open': 'Відкрити',
		'home': 'Домівка',
		'create': 'Створити',
		'broadcast': 'Транслювати',
		'settings': 'Налаштування',
		'email-address': 'Електронна пошта',
		'password': 'Пароль',
		'password-confirm': 'Підтвердіть пароль',
		'generate-question': 'Все ще не маєте гаманця?',
		'generate-it': '<a href="#/create">Згенеруйте</a> його!',
		'wif-key': 'Приватний ключ WIF',
		'create-wallet': 'Створити гаманець',
		'show': 'Показати',
		'hide': 'Сховати',
		'address': 'Адреса',
		'public-key': 'Публічний Ключ',
		'private-key': 'Приватний Ключ',
		'broadcast-transaction': 'Транслювати транзакцію',
		'enter-transaction': 'Введіть вашу підписану транзакцію',
		'wallet-settings': 'Налаштування гаманця',
		'address-type': 'Тип Адреси',
		'wallet-backend': 'Бекенд Гаманця',
		'update': 'Оновити',
		'wallet-language': 'Мова Гаманця',
		'version': 'Версія:',
		'wallet': 'Гаманець',
		'close': 'Закрити',
		'send': 'Надіслати',
		'history': 'Історія',
		'keys': 'Ключі',
		'reset': 'Скинути',
		'available-balance': 'Доступний баланс:',
		'enter-address': 'Введіть адресу',
		'amount': 'Сума',
		'fee': 'Комісія',
		'recommended': 'рекомендовано',
		'loading': 'Завантаження...',
		'send-sure': 'Ви впевенені?',
		'send-processing': 'Обробка...',
		'success': 'Успіх',
		'failed': 'Невдача',
		'send-it': 'Так, надіслати!',
		'cancel': 'Скасувати',
		'send-warning': 'Ви в одному кроці від того, щоб надіслати',
		'send-warning-reverse': 'Ця дія <strong>не може</strong> бути скасованою. Ви впевнені?',
		'loading-utxo': 'Завантаження UTXOs...',
		'transaction-creation': 'Створення транзакції...',
		'transaction-broadcasted': 'Транзакція успішно надіслана: ',
		'close': 'Закрити',
		'address-type-changed': 'Тип адрес змінений на',
		'backend-switched': 'Бекенд змінений на',
		'backend-down': 'виглядає мертвим',
		'wallet-api': 'API Бекенд гаманця',
		'open-wallet': 'Відкрити Гаманець',
		'bad-utxo': 'Непідтримуваний тип UTXO!',
		'balance-load-failed': 'Нам не вдалося завантажити баланс вашого гаманця!',
		'not-enough-funds': 'У вас не достатньо коштів для цієї транзакції!',
		'not-valid-address': 'Ви маєте ввести дійсну адресу!',
		'not-valid-amount': 'Ви маєте ввести дійсну суму!',
		'not-valid-fee': 'Ви маєте ввести дійсну комісію!',
		'bad-priv-key': 'Недійсний WIF приватний ключ WIF!',
		'not-enough-utxo': 'Не достатньо UTXO :(',
		'broadcast-failed': 'Не вдалося транслювати транзакцію :(',
		'pass-not-match': 'Паролі не не збігаються!',
		'pass-too-short': 'Ваш пароль повинен бути не менше 10 символів!',
		'bad-email': 'Схоже, що ви ввели не дійсну поштову скриньку!',
		'small-fee': 'Ви маєте задати комісію не менше ніж'
	}
}